# Generated by Django 4.2.7 on 2024-03-27 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=12)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('1', 'Terminal'), ('2', 'Oficina'), ('3', 'Paradero')], default='1', max_length=2)),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_veh', models.CharField(max_length=5)),
                ('placa_veh', models.CharField(max_length=8)),
                ('asientos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=2)),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programacion.propietario')),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('programacion', models.DateTimeField()),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(75000)])),
                ('estado', models.CharField(choices=[('0', 'Cancelado'), ('1', 'Programado'), ('2', 'Despachado')], default=1, max_length=2)),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.conductor')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='programacion.sede')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='programacion.sede')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_envio', models.CharField(max_length=100)),
                ('cedula_envio', models.CharField(max_length=12)),
                ('telefono_envio', models.CharField(max_length=12)),
                ('nombre_recibido', models.CharField(max_length=100)),
                ('cedula_recibido', models.CharField(max_length=12)),
                ('telefono_recibido', models.CharField(max_length=12)),
                ('costo_envio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(75000)])),
                ('estado', models.CharField(choices=[('1', 'Programada'), ('2', 'Despachada'), ('3', 'Cancelada'), ('4', 'Retornada')], default=1, max_length=2)),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.programacion')),
            ],
        ),
    ]
