# Generated by Django 5.0.4 on 2024-04-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_nombre', models.CharField(max_length=30)),
                ('class_usuario', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=30)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.sede')),
            ],
        ),
    ]
